package util;

import junit.framework.*;

public class RandoopTest0 extends TestCase {

  public static boolean debug = false;

  public void test1() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test1");


    br.com.addvisor.webservice.util.Note var0 = new br.com.addvisor.webservice.util.Note();

  }

  public void test2() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test2");


    br.com.addvisor.webservice.util.Constants var0 = new br.com.addvisor.webservice.util.Constants();

  }

  public void test3() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test3");


    br.com.addvisor.webservice.util.Tables var0 = new br.com.addvisor.webservice.util.Tables();

  }

  public void test4() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test4");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var3 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test5() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test5");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var4 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test6() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test6");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var2 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test7() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test7");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var1 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test8() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test8");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var5 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test9() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test9");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var6 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test10() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test10");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var7 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test11() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test11");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var8 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test12() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test12");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var10 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test13() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test13");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var9 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test14() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test14");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var11 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test15() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test15");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var12 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test16() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test16");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var13 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test17() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test17");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var14 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test18() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test18");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var15 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test19() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test19");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var17 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test20() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test20");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var16 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test21() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test21");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var18 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test22() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test22");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var19 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test23() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test23");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var20 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test24() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test24");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var23 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test25() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test25");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var22 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test26() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test26");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var25 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test27() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test27");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var21 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test28() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test28");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var27 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test29() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test29");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var28 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test30() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test30");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var26 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test31() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test31");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var24 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test32() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test32");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var29 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test33() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test33");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var31 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test34() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test34");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var30 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test35() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test35");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var32 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test36() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test36");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var33 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test37() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test37");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var35 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test38() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test38");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var34 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test39() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test39");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var36 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test40() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test40");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var37 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test41() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test41");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var38 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test42() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test42");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var39 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test43() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test43");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var40 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test44() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test44");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var42 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test45() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test45");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var41 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test46() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test46");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var43 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test47() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test47");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var44 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test48() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test48");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var45 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test49() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test49");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var46 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test50() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test50");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var47 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test51() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test51");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var48 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test52() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test52");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var49 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test53() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test53");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var50 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test54() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test54");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var51 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test55() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test55");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var52 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test56() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test56");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var53 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test57() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test57");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var54 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test58() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test58");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var55 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test59() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test59");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var57 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test60() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test60");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var56 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test61() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test61");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var59 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test62() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test62");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var58 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test63() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test63");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var60 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test64() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test64");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var61 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test65() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test65");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var62 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test66() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test66");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var63 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test67() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test67");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var65 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test68() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test68");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var64 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test69() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test69");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var66 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test70() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test70");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var67 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test71() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test71");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var68 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test72() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test72");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var69 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test73() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test73");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var71 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test74() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test74");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var70 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test75() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test75");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var72 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test76() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test76");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var73 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test77() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test77");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var75 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test78() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test78");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var74 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test79() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test79");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var76 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test80() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test80");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var77 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test81() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test81");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var78 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test82() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test82");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var79 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test83() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test83");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var80 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test84() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test84");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var81 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test85() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test85");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var82 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test86() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test86");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var84 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test87() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test87");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var83 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test88() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test88");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var85 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test89() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test89");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var87 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test90() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test90");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var86 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test91() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test91");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var88 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test92() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test92");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var90 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test93() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test93");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var89 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test94() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test94");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var92 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test95() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test95");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var91 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test96() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test96");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var94 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test97() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test97");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var93 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test98() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test98");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var98 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test99() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test99");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var96 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test100() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test100");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var95 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test101() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test101");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test102() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test102");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var99 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

  public void test103() throws Throwable {

    if (debug) System.out.printf("%nRandoopTest0.test103");


    br.com.addvisor.webservice.util.EntityFactory var0 = br.com.addvisor.webservice.util.EntityFactory.getInstance();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    var0.close();
    // The following exception was thrown during execution.
    // This behavior will recorded for regression testing.
    try {
      javax.persistence.EntityManager var97 = var0.createEntityManager();
      fail("Expected exception of type java.lang.IllegalStateException");
    } catch (java.lang.IllegalStateException e) {
      // Expected exception.
    }
    
    
    // Regression assertion (captures the current behavior of the code)
    assertNotNull(var0);

  }

}
